---
title: "Test_case"
author: "Joshua Ferreri"
date: "April 28, 2016"
output: html_document
---

```{r}
##to be added before generating the `precip_file` to update Miami FIPS to be
##consistant with other data sets in package
##It does not look like Miami FIPS are in this file:
"12025" %in% precip_file$fips
"55131" %in% precip_file$fips ##i know this value is in the data set
 ##Try to add DC into the closest_dist data set
load("/Users/joshuaferreri/Documents/HurricaneTracks.r")
study.states <- c('maine', 'new hampshire', 'vermont',                'massachusetts', 'connecticut', 'new york', 'rhode island',
        'new jersey', 'delaware', 'pennsylvania', 'maryland',                'virginia', 'north carolina', 'south carolina', 'georgia',          'florida', 'alabama', 'mississippi', 'louisiana', 'texas',            'west virginia', 'arkansas', 'tennessee', 'kentucky',
	'oklahoma', 'missouri', 'illinois', 'kentucky', 'indiana',
	'michigan', 'ohio', 'wisconsin', 'kansas', 'iowa', 'district of columbia')
study.state.fips <- state.fips$fips[state.fips$polyname %in%
        study.states]
study.state.fips <- c(study.state.fips, 25, 26, 36, 37, 51)
county.centers <-
        read.csv("/Users/joshuaferreri/Documents/CenPop2010_Mean_CO.txt", header = TRUE, skip = 2)
county.centers <- subset(county.centers,
	STATEFP %in% study.state.fips)
closest.storm.dates <- vector("list", length(hurr.tracks))
names(closest.storm.dates) <- names(hurr.tracks)

for(hurr in names(hurr.tracks)){
        print(hurr)
	ex <- hurr.tracks[[hurr]]
	ex$latitude <- as.numeric(ex$latitude)
	ex$longitude <- -1 * as.numeric(ex$longitude)
	county.dists <- spDists(as.matrix(county.centers[,c("LONGITUDE", "LATITUDE")]),
		as.matrix(ex[,c("longitude", "latitude")]),
		longlat = TRUE)
	min.locs <- apply(county.dists, 1, which.min)
	min.dists <- apply(county.dists, 1, min)
	closest.storm.dates[[hurr]] <- data.frame(
		county.fips = county.centers$COUNTYFP,
    	state.fips = county.centers$STATEFP,
		county.lat = county.centers$LATITUDE,
		county.long = county.centers$LONGITUDE,
		closest.date = ex$date[min.locs],
		storm.lat = ex$latitude[min.locs],
		storm.long = ex$longitude[min.locs],
		storm.dist = min.dists,
		strength = ex$status[min.locs])
	closest.storm.dates[[hurr]]$fips <- paste0(
		formatC(closest.storm.dates[[hurr]]$state.fips, width = 2,
			format = "d", flag = "0"),
		formatC(closest.storm.dates[[hurr]]$county.fips, width = 3,
			format = "d", flag = "0"))
}
save(closest.storm.dates,
	file = "/Users/joshuaferreri/Documents/ClosestStormDates.Rdata") # This has the DC FIPS ("11001") and the Miami FIPS of "12086".
```


#Generating `precip_file` with DC FIPS and Miami FIPS
```{r}
library(dplyr)
library(tidyr)
library(lubridate)
library(data.table)

load("/Users/joshuaferreri/Documents/ClosestStormDates.Rdata")
closest_dist <- do.call("rbind", closest.storm.dates)
closest_dist <- closest_dist[ , c("fips", "closest.date", "storm.dist")]
closest_dist$storm_id <- rep(names(closest.storm.dates),
                            each = nrow(closest.storm.dates[[1]]))
rownames(closest_dist) <- NULL
closest_dist <- closest_dist[ , c("storm_id", "fips",
                                  "closest.date", "storm.dist")]
colnames(closest_dist)[3:4] <- c("closest_date", "storm_dist")
closest_dist$closest_date <- ymd_hm(closest_dist$closest_date)

check_dates <- select(closest_dist, -storm_dist) %>%
        rename(day_0 = closest_date) %>%
        mutate(fips = as.integer(fips),
               day_0 = day_0 + days(0),
               day_b1 = day_0 - days(1),
               day_b2 = day_0 - days(2),
               day_b3 = day_0 - days(3),
               day_a1 = day_0 + days(1),
               day_a2 = day_0 + days(2),
               day_a3 = day_0 + days(3)) %>%
        select(storm_id, fips, day_b3, day_b2, day_b1,
               day_0, day_a1, day_a2, day_a3) %>%
        gather(key = lag, value = day, -storm_id, -fips) %>%
        mutate(day = as.numeric(format(day, "%Y%m%d")))
all_dates <- unique(check_dates$day)
all_fips <- unique(check_dates$fips) #has Miami as "12086", and is still in check_dates here
all_fips <- c(all_fips, as.integer(12025))
check_dates[check_dates$fips == 12086, "fips"] <- 12025
## Read and process precipitation data
precip_file <- fread("data-raw/nasa_precip_export_2.txt",
                           nrows = 500000,
                     header = TRUE,
                     select = c("county", "year_month_day", "precip")) %>%
        filter(county %in% all_fips,
               year_month_day %in% all_dates) %>%
        rename(fips = county, day = year_month_day) %>%
        right_join(data.table(check_dates),
                  by = c("fips" = "fips", "day" = "day")) %>%
        filter(!is.na(precip)) %>%
        select(-day) %>%
        spread(key = lag, value = precip) %>%
        arrange(storm_id, fips) %>%
        select(fips, storm_id, day_b3, day_b2, day_b1, day_0,
               day_a1, day_a2, day_a3) %>%
        mutate(fips = sprintf("%05d", fips))
precip_file[precip_file$fips == 12025, "fips"] <- 12086
```

# Begin experimenting with major hurricanes (mortality and economic burden)

```{r}
#Required Libraries
library(lubridate)
library(ggplot2)
library(devtools)
install_github("geanders/hurricaneexposure", 
               build_vignettes = TRUE)
library(hurricaneexposure)
library(weathermetrics)
```

##Hurricane Katrina, 2005

```{r}
#Plot Precipitation and Katrina Track
katrina_map <- map_counties(storm = "Katrina-2005", metric = "rainfall")
katrina_map 
katrina_tracks <- map_tracks(storm = "Katrina-2005", storm_status = TRUE, plot_object = katrina_map)
katrina_tracks
#Max rain for Katrina
katrina <- precip_file[precip_file$storm_id == "Katrina-2005",]
max(katrina$day_0)
convert_precip(max(katrina$day_0), "mm", "inches")
```

##Floyd, 1999

```{r}
#Floyd precip and track
floyd_map <- map_counties(storm = "Floyd-1999", metric = "rainfall")
floyd_tracks <- map_tracks(storm = "Floyd-1999", storm_status = TRUE, plot_object = floyd_map)
floyd_tracks
#Max rain Floyd
floyd <- precip_file[precip_file$storm_id == "Floyd-1999", ]
convert_precip(max(floyd$day_0), "mm", "inches")
```

##Hurricane Andrew, 1992


##Set up loop to map all hurricanes of interest 

```{r}
#Hurricane tracks and precip for: Katrina, Floyd, Andrew, Ike, Wilma, and Charley
my_hurricanes <- c("Katrina-2005", "Floyd-1999", "Andrew-1992", "Ike-2008", "Wilma-2005", "Charley-2004")
for(hurricane in my_hurricanes){
        hurricane_map <- map_counties(storm = hurricane, 
                                      metric = "rainfall")
        hurricane_track <- map_tracks(storm = hurricane, 
                                      storm_status = TRUE, 
                                      plot_object = hurricane_map)
        print(hurricane_track)
}
```
